<?php
	require('Core/core.php');
	if(isset($_GET["view"])){
		if(file_exists('Core/Controllers/'.strtolower($_GET["view"]).'Controller.php')){
			include('Core/Controllers/'.strtolower($_GET["view"]).'Controller.php');
		}else{
			include('Core/Controllers/errorController.php');
		}
	}else{
		include('Core/Controllers/indexController.php');
	}
?>